{"uuid": "26d3b84e-fd68-4e4d-ac04-ece135751b28", "children": ["9e903fc3-52dd-41b2-9863-dc637a0c3e9e"], "befores": [{"name": "driver", "status": "passed", "start": 1675723822695, "stop": 1675723824922}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: You clicked a button\nMessage: unexpected alert open: {Alert text : You clicked a button}\n  (Session info: chrome=109.0.5414.120)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00F26643]\n\t(No symbol) [0x00EBBE21]\n\t(No symbol) [0x00DBDA9D]\n\t(No symbol) [0x00E273A5]\n\t(No symbol) [0x00E0FB76]\n\t(No symbol) [0x00DE49C1]\n\t(No symbol) [0x00DE5E5D]\n\tGetHandleVerifier [0x0119A142+2497106]\n\tGetHandleVerifier [0x011C85D3+2686691]\n\tGetHandleVerifier [0x011CBB9C+2700460]\n\tGetHandleVerifier [0x00FD3B10+635936]\n\t(No symbol) [0x00EC4A1F]\n\t(No symbol) [0x00ECA418]\n\t(No symbol) [0x00ECA505]\n\t(No symbol) [0x00ED508B]\n\tBaseThreadInitThunk [0x752300F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77177BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77177B8E+238]\n\n", "trace": "  File \"D:\\automation_QA\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\automation_QA\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\automation_QA\\conftest.py\", line 15, in driver\n    attach = driver.get_screenshot_as_png()\n  File \"D:\\automation_QA\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 926, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"D:\\automation_QA\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 937, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"D:\\automation_QA\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\automation_QA\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 244, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n"}, "start": 1675723826663, "stop": 1675723826667}], "start": 1675723822695, "stop": 1675723826667}